name: lint

on: [push, pull_request]

jobs:
  fmt:
    name: fmt (${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt

      - name: Run cargo fmt
        run: cargo +${{ matrix.rust }} fmt --all -- --check

  clippy:
    name: clippy (${{ matrix.rust }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - name: Smart Cache
        uses: Swatinem/rust-cache@v2

      - name: Update Dependencies
        run: cargo update

      - name: Run cargo clippy
        run: cargo +${{ matrix.rust }} clippy --all-features -- -D warnings
